spring:
  application:
    name: APIBridge
  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_ADDR:localhost}
      port: ${REDIS_PORT:6379}

app:
  google:
    apiKey: ""
    baseUrl: "https://www.googleapis.com/books/v1/"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8090 #different port that global for access locally and not serve by web server.

  endpoint:
    health:
      show-details: always