spring:
  application:
    name: APIBridge
  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_ADDR:localhost}
      port: ${REDIS_PORT:6379}

app:
  google:
    apiKey: ""
    baseUrl: "https://www.googleapis.com/books/v1/"

  finnotech:
    base-url: "https://api.finnotech.ir"
    nid: ${FINNOTECH_NID}
    scopes: "credit:cheque-color-inquiry:get,kyc:sms-shahkar-send:get,kyc:sms-shahkar-verification:get,kyc:iban-owner-verification:get,facility:shahkar:get"
    client-id: ${FINNOTECH_CLIENT_ID}
    client-secret: ${FINNOTECH_CLIENT_SECRET}


management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8090 #different port that global for access locally and not serve by web server.

  endpoint:
    health:
      show-details: always